# Generated by Django 5.1.5 on 2025-02-04 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('full_address', models.TextField()),
                ('post_code', models.CharField(max_length=10)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_cases', to='core.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_cases', to='core.country')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_cases', to='core.province')),
            ],
        ),
    ]
